version: '2'
services:
  spingularmongochat2-app:
    image: spingularmongochat2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://spingularmongochat2-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=spingularmongochat2
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  spingularmongochat2-mongodb:
    extends:
      file: mongodb.yml
      service: spingularmongochat2-mongodb
